//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 09:28:41 AM BST 
//


package com.kuoni.finance.jaxb.obsapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_AddBookingItemRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_AddBookingItemRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BookingReference" type="{}t_BookingReferenceInput"/>
 *         &lt;element name="BookingItems" type="{}t_BookingItems" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_AddBookingItemRequest", propOrder = {
    "bookingReference",
    "bookingItems"
})
@XmlRootElement(name="AddBookingItemRequest")
public class TAddBookingItemRequest {

    @XmlElement(name = "BookingReference", required = true)
    protected TBookingReferenceInput bookingReference;
    @XmlElement(name = "BookingItems")
    protected TBookingItems bookingItems;

    /**
     * Gets the value of the bookingReference property.
     * 
     * @return
     *     possible object is
     *     {@link TBookingReferenceInput }
     *     
     */
    public TBookingReferenceInput getBookingReference() {
        return bookingReference;
    }

    /**
     * Sets the value of the bookingReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBookingReferenceInput }
     *     
     */
    public void setBookingReference(TBookingReferenceInput value) {
        this.bookingReference = value;
    }

    /**
     * Gets the value of the bookingItems property.
     * 
     * @return
     *     possible object is
     *     {@link TBookingItems }
     *     
     */
    public TBookingItems getBookingItems() {
        return bookingItems;
    }

    /**
     * Sets the value of the bookingItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBookingItems }
     *     
     */
    public void setBookingItems(TBookingItems value) {
        this.bookingItems = value;
    }

}
