//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 09:28:41 AM BST 
//


package com.kuoni.finance.jaxb.obsapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_AOTNumbers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_AOTNumbers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="International" type="{}t_Phone" minOccurs="0"/>
 *         &lt;element name="National" type="{}t_Phone" minOccurs="0"/>
 *         &lt;element name="Local" type="{}t_Phone" minOccurs="0"/>
 *         &lt;element name="OutOfOffice" type="{}t_Phone" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_AOTNumbers", propOrder = {
    "international",
    "national",
    "local",
    "outOfOffice"
})
public class TAOTNumbers {

    @XmlElement(name = "International")
    protected String international;
    @XmlElement(name = "National")
    protected String national;
    @XmlElement(name = "Local")
    protected String local;
    @XmlElement(name = "OutOfOffice")
    protected String outOfOffice;

    /**
     * Gets the value of the international property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternational() {
        return international;
    }

    /**
     * Sets the value of the international property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternational(String value) {
        this.international = value;
    }

    /**
     * Gets the value of the national property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNational() {
        return national;
    }

    /**
     * Sets the value of the national property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNational(String value) {
        this.national = value;
    }

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocal(String value) {
        this.local = value;
    }

    /**
     * Gets the value of the outOfOffice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutOfOffice() {
        return outOfOffice;
    }

    /**
     * Sets the value of the outOfOffice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutOfOffice(String value) {
        this.outOfOffice = value;
    }

}
