//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 09:28:41 AM BST 
//


package com.kuoni.finance.jaxb.obsapi;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_ApartmentUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_ApartmentUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApartmentUnitName" type="{}t_ApartmentUnitName" minOccurs="0"/>
 *         &lt;element name="Meals" type="{}t_Meals" minOccurs="0"/>
 *         &lt;element name="UnitPrice" type="{}t_PriceDetails" minOccurs="0"/>
 *         &lt;element name="Confirmation" type="{}t_ItemConfirmation" minOccurs="0"/>
 *         &lt;element name="ApartmentUnitRooms" type="{}t_ApartmentUnitRooms" minOccurs="0"/>
 *         &lt;element name="ApartmentUnitFacilities" type="{}t_ApartmentUnitFacilities" minOccurs="0"/>
 *         &lt;element name="Links" type="{}t_Links" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}a_Apartment"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_ApartmentUnit", propOrder = {
    "apartmentUnitName",
    "meals",
    "unitPrice",
    "confirmation",
    "apartmentUnitRooms",
    "apartmentUnitFacilities",
    "links"
})
public class TApartmentUnit {

    @XmlElement(name = "ApartmentUnitName")
    protected TApartmentUnitName apartmentUnitName;
    @XmlElement(name = "Meals")
    protected TMeals meals;
    @XmlElement(name = "UnitPrice")
    protected TPriceDetails unitPrice;
    @XmlElement(name = "Confirmation")
    protected TItemConfirmation confirmation;
    @XmlElement(name = "ApartmentUnitRooms")
    protected TApartmentUnitRooms apartmentUnitRooms;
    @XmlElement(name = "ApartmentUnitFacilities")
    protected TApartmentUnitFacilities apartmentUnitFacilities;
    @XmlElement(name = "Links")
    protected TLinks links;
    @XmlAttribute(name = "Code")
    protected String code;
    @XmlAttribute(name = "Sleeps")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sleeps;
    @XmlAttribute(name = "NumberOfCots")
    protected Integer numberOfCots;

    /**
     * Gets the value of the apartmentUnitName property.
     * 
     * @return
     *     possible object is
     *     {@link TApartmentUnitName }
     *     
     */
    public TApartmentUnitName getApartmentUnitName() {
        return apartmentUnitName;
    }

    /**
     * Sets the value of the apartmentUnitName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TApartmentUnitName }
     *     
     */
    public void setApartmentUnitName(TApartmentUnitName value) {
        this.apartmentUnitName = value;
    }

    /**
     * Gets the value of the meals property.
     * 
     * @return
     *     possible object is
     *     {@link TMeals }
     *     
     */
    public TMeals getMeals() {
        return meals;
    }

    /**
     * Sets the value of the meals property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMeals }
     *     
     */
    public void setMeals(TMeals value) {
        this.meals = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link TPriceDetails }
     *     
     */
    public TPriceDetails getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPriceDetails }
     *     
     */
    public void setUnitPrice(TPriceDetails value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the confirmation property.
     * 
     * @return
     *     possible object is
     *     {@link TItemConfirmation }
     *     
     */
    public TItemConfirmation getConfirmation() {
        return confirmation;
    }

    /**
     * Sets the value of the confirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TItemConfirmation }
     *     
     */
    public void setConfirmation(TItemConfirmation value) {
        this.confirmation = value;
    }

    /**
     * Gets the value of the apartmentUnitRooms property.
     * 
     * @return
     *     possible object is
     *     {@link TApartmentUnitRooms }
     *     
     */
    public TApartmentUnitRooms getApartmentUnitRooms() {
        return apartmentUnitRooms;
    }

    /**
     * Sets the value of the apartmentUnitRooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TApartmentUnitRooms }
     *     
     */
    public void setApartmentUnitRooms(TApartmentUnitRooms value) {
        this.apartmentUnitRooms = value;
    }

    /**
     * Gets the value of the apartmentUnitFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link TApartmentUnitFacilities }
     *     
     */
    public TApartmentUnitFacilities getApartmentUnitFacilities() {
        return apartmentUnitFacilities;
    }

    /**
     * Sets the value of the apartmentUnitFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link TApartmentUnitFacilities }
     *     
     */
    public void setApartmentUnitFacilities(TApartmentUnitFacilities value) {
        this.apartmentUnitFacilities = value;
    }

    /**
     * Gets the value of the links property.
     * 
     * @return
     *     possible object is
     *     {@link TLinks }
     *     
     */
    public TLinks getLinks() {
        return links;
    }

    /**
     * Sets the value of the links property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLinks }
     *     
     */
    public void setLinks(TLinks value) {
        this.links = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the sleeps property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSleeps() {
        return sleeps;
    }

    /**
     * Sets the value of the sleeps property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSleeps(BigInteger value) {
        this.sleeps = value;
    }

    /**
     * Gets the value of the numberOfCots property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfCots() {
        return numberOfCots;
    }

    /**
     * Sets the value of the numberOfCots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfCots(Integer value) {
        this.numberOfCots = value;
    }

}
