//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 09:28:41 AM BST 
//


package com.kuoni.finance.jaxb.obsapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_Apartment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_Apartment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="City" type="{}t_City"/>
 *         &lt;element name="Item" type="{}t_Item"/>
 *         &lt;element name="LocationDetails" type="{}t_LocationDetails" minOccurs="0"/>
 *         &lt;element name="StarRating" type="{}t_StarRating" minOccurs="0"/>
 *         &lt;element name="CheckInDays" type="{}t_CheckInDays" minOccurs="0"/>
 *         &lt;element name="PeriodOfStay" type="{}t_PeriodOfStay" minOccurs="0"/>
 *         &lt;element name="EssentialInformation" type="{}t_EssentialInformation" minOccurs="0"/>
 *         &lt;element name="ApartmentUnits" type="{}t_ApartmentUnits" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}a_Hotel"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_Apartment", propOrder = {
    "city",
    "item",
    "locationDetails",
    "starRating",
    "checkInDays",
    "periodOfStay",
    "essentialInformation",
    "apartmentUnits"
})
public class TApartment {

    @XmlElement(name = "City", required = true)
    protected TCity city;
    @XmlElement(name = "Item", required = true)
    protected TItem item;
    @XmlElement(name = "LocationDetails")
    protected TLocationDetails locationDetails;
    @XmlElement(name = "StarRating")
    protected TStarRating starRating;
    @XmlElement(name = "CheckInDays")
    protected TCheckInDays checkInDays;
    @XmlElement(name = "PeriodOfStay")
    protected TPeriodOfStay periodOfStay;
    @XmlElement(name = "EssentialInformation")
    protected TEssentialInformation essentialInformation;
    @XmlElement(name = "ApartmentUnits")
    protected TApartmentUnits apartmentUnits;
    @XmlAttribute(name = "HasExtraInfo")
    protected Boolean hasExtraInfo;
    @XmlAttribute(name = "HasMap")
    protected Boolean hasMap;
    @XmlAttribute(name = "HasPictures")
    protected Boolean hasPictures;
    @XmlAttribute(name = "HasImportantInfo")
    protected Boolean hasImportantInfo;
    @XmlAttribute(name = "Recommended")
    protected Boolean recommended;

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link TCity }
     *     
     */
    public TCity getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCity }
     *     
     */
    public void setCity(TCity value) {
        this.city = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link TItem }
     *     
     */
    public TItem getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link TItem }
     *     
     */
    public void setItem(TItem value) {
        this.item = value;
    }

    /**
     * Gets the value of the locationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TLocationDetails }
     *     
     */
    public TLocationDetails getLocationDetails() {
        return locationDetails;
    }

    /**
     * Sets the value of the locationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLocationDetails }
     *     
     */
    public void setLocationDetails(TLocationDetails value) {
        this.locationDetails = value;
    }

    /**
     * Gets the value of the starRating property.
     * 
     * @return
     *     possible object is
     *     {@link TStarRating }
     *     
     */
    public TStarRating getStarRating() {
        return starRating;
    }

    /**
     * Sets the value of the starRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link TStarRating }
     *     
     */
    public void setStarRating(TStarRating value) {
        this.starRating = value;
    }

    /**
     * Gets the value of the checkInDays property.
     * 
     * @return
     *     possible object is
     *     {@link TCheckInDays }
     *     
     */
    public TCheckInDays getCheckInDays() {
        return checkInDays;
    }

    /**
     * Sets the value of the checkInDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link TCheckInDays }
     *     
     */
    public void setCheckInDays(TCheckInDays value) {
        this.checkInDays = value;
    }

    /**
     * Gets the value of the periodOfStay property.
     * 
     * @return
     *     possible object is
     *     {@link TPeriodOfStay }
     *     
     */
    public TPeriodOfStay getPeriodOfStay() {
        return periodOfStay;
    }

    /**
     * Sets the value of the periodOfStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPeriodOfStay }
     *     
     */
    public void setPeriodOfStay(TPeriodOfStay value) {
        this.periodOfStay = value;
    }

    /**
     * Gets the value of the essentialInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TEssentialInformation }
     *     
     */
    public TEssentialInformation getEssentialInformation() {
        return essentialInformation;
    }

    /**
     * Sets the value of the essentialInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEssentialInformation }
     *     
     */
    public void setEssentialInformation(TEssentialInformation value) {
        this.essentialInformation = value;
    }

    /**
     * Gets the value of the apartmentUnits property.
     * 
     * @return
     *     possible object is
     *     {@link TApartmentUnits }
     *     
     */
    public TApartmentUnits getApartmentUnits() {
        return apartmentUnits;
    }

    /**
     * Sets the value of the apartmentUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link TApartmentUnits }
     *     
     */
    public void setApartmentUnits(TApartmentUnits value) {
        this.apartmentUnits = value;
    }

    /**
     * Gets the value of the hasExtraInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasExtraInfo() {
        return hasExtraInfo;
    }

    /**
     * Sets the value of the hasExtraInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasExtraInfo(Boolean value) {
        this.hasExtraInfo = value;
    }

    /**
     * Gets the value of the hasMap property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasMap() {
        return hasMap;
    }

    /**
     * Sets the value of the hasMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasMap(Boolean value) {
        this.hasMap = value;
    }

    /**
     * Gets the value of the hasPictures property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasPictures() {
        return hasPictures;
    }

    /**
     * Sets the value of the hasPictures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasPictures(Boolean value) {
        this.hasPictures = value;
    }

    /**
     * Gets the value of the hasImportantInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasImportantInfo() {
        return hasImportantInfo;
    }

    /**
     * Sets the value of the hasImportantInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasImportantInfo(Boolean value) {
        this.hasImportantInfo = value;
    }

    /**
     * Gets the value of the recommended property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRecommended() {
        return recommended;
    }

    /**
     * Sets the value of the recommended property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecommended(Boolean value) {
        this.recommended = value;
    }

}
