//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 09:28:41 AM BST 
//


package com.kuoni.finance.jaxb.obsapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for t_ApartmentItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_ApartmentItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnitCode" type="{}t_ApartmentCode"/>
 *         &lt;element name="NumberOfCots" type="{}t_NumberOfCots" minOccurs="0"/>
 *         &lt;element name="PeriodOfStay" type="{}t_PeriodOfStay"/>
 *         &lt;element name="ArrivalDate" type="{}t_Date" minOccurs="0"/>
 *         &lt;element name="Meals" type="{}t_Meals" minOccurs="0"/>
 *         &lt;element name="PaxIds" type="{}t_PaxIds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_ApartmentItem", propOrder = {
    "unitCode",
    "numberOfCots",
    "periodOfStay",
    "arrivalDate",
    "meals",
    "paxIds"
})
public class TApartmentItem {

    @XmlElement(name = "UnitCode", required = true)
    protected String unitCode;
    @XmlElement(name = "NumberOfCots")
    protected Integer numberOfCots;
    @XmlElement(name = "PeriodOfStay", required = true)
    protected TPeriodOfStay periodOfStay;
    @XmlElement(name = "ArrivalDate")
    protected XMLGregorianCalendar arrivalDate;
    @XmlElement(name = "Meals")
    protected TMeals meals;
    @XmlElement(name = "PaxIds", required = true)
    protected TPaxIds paxIds;

    /**
     * Gets the value of the unitCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * Sets the value of the unitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCode(String value) {
        this.unitCode = value;
    }

    /**
     * Gets the value of the numberOfCots property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfCots() {
        return numberOfCots;
    }

    /**
     * Sets the value of the numberOfCots property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfCots(Integer value) {
        this.numberOfCots = value;
    }

    /**
     * Gets the value of the periodOfStay property.
     * 
     * @return
     *     possible object is
     *     {@link TPeriodOfStay }
     *     
     */
    public TPeriodOfStay getPeriodOfStay() {
        return periodOfStay;
    }

    /**
     * Sets the value of the periodOfStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPeriodOfStay }
     *     
     */
    public void setPeriodOfStay(TPeriodOfStay value) {
        this.periodOfStay = value;
    }

    /**
     * Gets the value of the arrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrivalDate() {
        return arrivalDate;
    }

    /**
     * Sets the value of the arrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrivalDate(XMLGregorianCalendar value) {
        this.arrivalDate = value;
    }

    /**
     * Gets the value of the meals property.
     * 
     * @return
     *     possible object is
     *     {@link TMeals }
     *     
     */
    public TMeals getMeals() {
        return meals;
    }

    /**
     * Sets the value of the meals property.
     * 
     * @param value
     *     allowed object is
     *     {@link TMeals }
     *     
     */
    public void setMeals(TMeals value) {
        this.meals = value;
    }

    /**
     * Gets the value of the paxIds property.
     * 
     * @return
     *     possible object is
     *     {@link TPaxIds }
     *     
     */
    public TPaxIds getPaxIds() {
        return paxIds;
    }

    /**
     * Sets the value of the paxIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPaxIds }
     *     
     */
    public void setPaxIds(TPaxIds value) {
        this.paxIds = value;
    }

}
