//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 09:28:41 AM BST 
//


package com.kuoni.finance.jaxb.obsapi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_ApartmentUnitsPriceBreakdown complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_ApartmentUnitsPriceBreakdown">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ApartmentUnit" type="{}t_ApartmentUnitPriceBreakdown" maxOccurs="9"/>
 *         &lt;element name="ItemSupplements" type="{}t_ItemSupplements" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_ApartmentUnitsPriceBreakdown", propOrder = {
    "apartmentUnit",
    "itemSupplements"
})
public class TApartmentUnitsPriceBreakdown {

    @XmlElement(name = "ApartmentUnit", required = true)
    protected List<TApartmentUnitPriceBreakdown> apartmentUnit;
    @XmlElement(name = "ItemSupplements")
    protected TItemSupplements itemSupplements;

    /**
     * Gets the value of the apartmentUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the apartmentUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApartmentUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TApartmentUnitPriceBreakdown }
     * 
     * 
     */
    public List<TApartmentUnitPriceBreakdown> getApartmentUnit() {
        if (apartmentUnit == null) {
            apartmentUnit = new ArrayList<TApartmentUnitPriceBreakdown>();
        }
        return this.apartmentUnit;
    }

    /**
     * Gets the value of the itemSupplements property.
     * 
     * @return
     *     possible object is
     *     {@link TItemSupplements }
     *     
     */
    public TItemSupplements getItemSupplements() {
        return itemSupplements;
    }

    /**
     * Sets the value of the itemSupplements property.
     * 
     * @param value
     *     allowed object is
     *     {@link TItemSupplements }
     *     
     */
    public void setItemSupplements(TItemSupplements value) {
        this.itemSupplements = value;
    }

}
