//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 09:28:41 AM BST 
//


package com.kuoni.finance.jaxb.obsapi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_AvailabilityCacheRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_AvailabilityCacheRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ItemDestinations" type="{}t_ItemDestinations"/>
 *         &lt;element name="CacheDataFormatPL2" type="{}t_Empty" minOccurs="0"/>
 *         &lt;element name="DateRange" type="{}t_DateRange"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_AvailabilityCacheRequest", propOrder = {
    "itemDestinations",
    "cacheDataFormatPL2",
    "dateRange"
})
public class TAvailabilityCacheRequest {

    @XmlElement(name = "ItemDestinations", required = true)
    protected TItemDestinations itemDestinations;
    @XmlElement(name = "CacheDataFormatPL2")
    protected TEmpty cacheDataFormatPL2;
    @XmlElement(name = "DateRange", required = true)
    protected TDateRange dateRange;

    /**
     * Gets the value of the itemDestinations property.
     * 
     * @return
     *     possible object is
     *     {@link TItemDestinations }
     *     
     */
    public TItemDestinations getItemDestinations() {
        return itemDestinations;
    }

    /**
     * Sets the value of the itemDestinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TItemDestinations }
     *     
     */
    public void setItemDestinations(TItemDestinations value) {
        this.itemDestinations = value;
    }

    /**
     * Gets the value of the cacheDataFormatPL2 property.
     * 
     * @return
     *     possible object is
     *     {@link TEmpty }
     *     
     */
    public TEmpty getCacheDataFormatPL2() {
        return cacheDataFormatPL2;
    }

    /**
     * Sets the value of the cacheDataFormatPL2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEmpty }
     *     
     */
    public void setCacheDataFormatPL2(TEmpty value) {
        this.cacheDataFormatPL2 = value;
    }

    /**
     * Gets the value of the dateRange property.
     * 
     * @return
     *     possible object is
     *     {@link TDateRange }
     *     
     */
    public TDateRange getDateRange() {
        return dateRange;
    }

    /**
     * Sets the value of the dateRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDateRange }
     *     
     */
    public void setDateRange(TDateRange value) {
        this.dateRange = value;
    }

}
